version: v2beta1
name: devspace-control-tower


dependencies:
  publisher-backend:
     path: ./services/publisher-backend
     pipeline: dev


pipelines:
  # Run this pipeline via  `devspace run-pipeline setup-workspace`
  deploy:
    run: |-
      run_dependencies --all       # 1. Deploy any projects this project needs (see "dependencies")
      ensure_pull_secrets --all    # 2. Ensure pull secrets
      create_deployments --all     # 3. Deploy Helm charts and manifests specified as "deployments"
