apiVersion: apps/v1
kind: Deployment
metadata:
  name: scorer-backend
  labels:
    app: scorer-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scorer-backend
  template:
    metadata:
      labels:
        app: scorer-backend
    spec:
      containers:
        - name: scorer-backend
          image: "{{ .Values.image.repository }}"