apiVersion: v1
kind: Service
metadata:
  name: scorer-backend-service
  labels:
    app: scorer-backend
spec:
  type: LoadBalancer
  selector:
    app: scorer-backend
  ports:
    - name: http
      port: 80
      targetPort: 5000
