version: v2beta1
name: scorer-backend-devspace

pipelines:
  dev:
    run: |-
      run_dependencies --all       # 1. Deploy any projects this project needs (see "dependencies")
      ensure_pull_secrets --all    # 2. Ensure pull secrets
      create_deployments --all     # 3. Deploy Helm charts and manifests specfied as "deployments"
      start_dev scorer-backend                # 4. Start dev mode "scorer-backend" (see "dev" section)
  deploy:
    run: |-
      run_dependencies --all                            # 1. Deploy any projects this project needs (see "dependencies")
      ensure_pull_secrets --all                         # 2. Ensure pull secrets
      build_images --all -t $(git describe --always)    # 3. Build, tag (git commit hash) and push all images (see "images")
      create_deployments --all                          # 4. Deploy Helm charts and manifests specfied as "deployments"

images:
  scorer-backend:
    image: my-image-registry.tld/username/scorer-backend
    tags:
      - rc
    dockerfile: ./Dockerfile

deployments:
  scorer-backend:
    helm:
      chart:
        name: ./helm
      values:
        someValue: someValue

dev:
  scorer-backend:
    imageSelector: my-image-registry.tld/username/scorer-backend:rc
    sync:
      - path: ./
    ssh:
      enabled: true
    proxyCommands:
      - command: devspace
      - command: kubectl
      - command: helm
      - gitCredentials: true
    ports:
      - port: "9003"
